
### User Information ###
# edit these to suit your country and timezone

timezone: Europe/London # follows tz database
tv_region: United Kingdom #follows the way the country appears in thesportsdb json
cache_ttl_mins: 60

### API settings ###
# only need to be editied if you are a premium user
premium: false #change to true if you have premium for "thesportsdb"
key: 123 #The current free "thesportsdb" API key is: 123, replace if you have a premium key
tv_lookup: false


### Sports ###
# fully supported sports, you can add your own sports just match them to the format below
# in this current version only football is supported

sports:
  Motorsports:
    f1:
      name: "Formula 1" #quoted for robustness
      enabled: false
  Football:
    CL:
        name: "Champions League"
        enabled: true
    PPL:
      name: "Primeira Liga"
      enabled: false
    PL:
      name: "Premier League"
      enabled: true
    DED:
      name: "Eredivisie"
      enabled: false
    BL1:
      name: "Bundesliga"
      enabled: false
    FL1:
      name: "Ligue 1"
      enabled: false
    SA:
      name: "Serie A"
      enabled: false
    PD:
      name: "La Liga"
      enabled: false
    ELC:
      name: "Championship"
      enabled: true
    BSA:
      name: "Brasileirão Série A"
      enabled: false
    WC:
      name: "Fifa World Cup"
      enabled: false
    EC:
      name: "Euros"
      enabled: false



